### ISSUE TITLE
Can you look over this description of the DeepLIFT implementation in your repository?

### ISSUE THREAD

**Issue by AvantiShri** [NPoe/neural-nlp-explanation-experiment#1]
Hello,

Thank you for this rigorous comparison. I'm the author of DeepLIFT, and I wanted to augment DeepLIFT's [FAQ](https://github.com/kundajelab/deeplift#how-does-the-implementation-in-this-repository-compare-with-poerner-et-al-acl-2018) section to compare the implementation there with the implementation in this repo. This is what I have - can you give your approval or suggest edits?

Poerner et al. conducted a series of benchmarks comparing DeepLIFT to other explanation methods on NLP tasks. Their implementation differs from the canonical DeepLIFT implementation in two main ways. First, they appear to have considered only the Rescale rule of DeepLIFT, based on the implementation [here](https://github.com/NPoe/neural-nlp-explanation-experiment/blob/master/HybridDocuments/ThirdParty/LRP_and_DeepLIFT/code/layers.py). Second, to handle operations that involve multiplications with gating units (which DeepLIFT was not designed for), they treat the gating neuron as a weight and assign all importance to the non-gating neuron. Note that this would differ from the implementation in Ancona et al., which would handle multiplications with gates using the standard gradient backpropagation rule (and thus would assign importance to the gating neuron). We have not studied the appropriateness of this approach, but the authors did find that "LIMSSE, LRP (Bach et al., 2015) and DeepLIFT (Shrikumar et al., 2017) are the most effective explanation methods (§4): LRP and DeepLIFT are the most consistent methods, while LIMSSE wins the hybrid document experiment."

**Comment by NPoe** [comment]
Hello,

That's a very accurate description. To give credit where it's due, I think you should also include a link to Leila Arras's paper or [repo](https://github.com/ArrasL/LRP_for_LSTM). She has come up with the treat-gates-as-weights idea; I have only extended it from LRP to DeepLIFT.

**Comment by AvantiShri** [comment]
Will do. Thanks!
