### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tangxiangru** [NPoe/neural-nlp-explanation-experiment#2]
python main.py prepare yelp
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from task_methods import *
  File "/home/txr/neural-nlp-explanation-experiment-master/HybridDocuments/SRC/task_methods.py", line 17, in <module>
    from explanation_methods import *
  File "/home/txr/neural-nlp-explanation-experiment-master/HybridDocuments/SRC/explanation_methods.py", line 140
    self.score_model.add(TimeDistributed(Dense(**dense_config,weights = dense.get_weights()[:1])))
                                                             ^
SyntaxError: invalid syntax

**Comment by NPoe** [comment]
Hi, which version of python are you using?

**Comment by tangxiangru** [comment]
Hi, this bug is caused by python2. BUT which version of keras  are you using?

**Comment by NPoe** [comment]
You will probably have to upgrade to python3.

This repo is based on my keras fork: https://github.com/NPoe/keras

The reason was that, at the time, keras did not support access to LSTM gates etc. (not sure if it does now). The fork is pretty outdated since I am no longer working on the project.

**Comment by tangxiangru** [comment]
So how to retrain your code with anaconda？

**Comment by NPoe** [comment]
Not sure about anaconda. I would do the following:

virtualenv -p python3 name_of_my_env
source name_of_my_env/bin/activate

git clone https://github.com/NPoe/keras npoe_keras
cd npoe_keras
python3 setup.py install
export KERAS_BACKEND=theano
pip3 install nltk sklearn
