### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'output_dim'

### ISSUE THREAD

**Issue by tangxiangru** [NPoe/neural-nlp-explanation-experiment#3]
(python-thn) [txr@localhost SRC]$ python main.py train newsgroup LSTM
Using TensorFlow backend.
Loading from ../Inputs/newsgroup/embeddings
Loading from ../Inputs/newsgroup/worddict
Loading from ../Inputs/newsgroup/classdict
Traceback (most recent call last):
  File "main.py", line 103, in <module>
    train(architecture, corpus)
  File "main.py", line 25, in train
    model.build()
  File "/home/txr/neural-nlp-explanation-experiment/HybridDocuments/SRC/task_methods.py", line 91, in build
    **config),
TypeError: __init__() missing 1 required positional argument: 'output_dim'

**Comment by NPoe** [comment]
In the interest of keeping this discussion in one thread, I will close this issue and reopen https://github.com/NPoe/neural-nlp-explanation-experiment/issues/2.
